### ISSUE TITLE
pnpm install for sandbox-agent 0.2.0 shows missing peer dependency "zod"

### ISSUE THREAD

**Issue by akalitenya** [rivet-dev/sandbox-agent#169]
maybe need to add "zod" as dependency if it is used or will be used for validation

**Comment by NathanFlurry** [comment]
can you share more details? one of our examples uses zod, but not the core package.

**Comment by akalitenya** [comment]
when I upgraded to 0.2.0 and run "pnpm inst" there were red warning (not yellow) "missing peer dependency" for "zod"

As I understand it may or may not break things depending how it is used in sdk. pnpm does not auto install peers if they are not specified in package.json.

So I added "zod" to package.json to remove warning

my dev branch - https://github.com/mprove-io/mprove/tree/ak1

**Comment by akalitenya** [comment]
found logs:

pnpm install log
```
...
WARN  Issues with peer dependencies found

libs/node-common
└─┬ @mprove/common 11.0.99-dev
  └─┬ sandbox-agent 0.2.0
    └─┬ acp-http-client 0.1.0
      └─┬ @agentclientprotocol/sdk 0.14.1
        └── ✕ missing peer zod@"^3.25.0 || ^4.0.0"
Peer dependencies that should be installed:
  zod@"^3.25.0 || ^4.0.0"
Done in 7.6s using pnpm v10.29.3
```

Claude:
```
The one that actually matters is the missing zod:

libs/common → sandbox-agent → acp-http-client → @agentclientprotocol/sdk → needs zod

zod is not installed at all. If sandbox-agent / @agentclientprotocol/sdk uses zod for runtime validation, 
it will crash with a Cannot find module 'zod' error when that code path runs. 
The fix is to add zod to the catalog in pnpm-workspace.yaml and as a dependency in libs/common/package.json.

The "missing peer" warning comes from libs/node-common:

libs/node-common
└─┬ @mprove/common 11.0.99-dev
  └─┬ sandbox-agent 0.2.0
    └─┬ acp-http-client 0.1.0
      └─┬ @agentclientprotocol/sdk 0.14.1
        └── ✕ missing peer zod@"^3.25.0 || ^4.0.0"

So libs/node-common depends on @mprove/common, which depends on sandbox-agent, 
which eventually needs zod as a peer dependency. 
I should add zod to libs/node-common to satisfy this requirement.
```
